import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, MapPin } from "lucide-react";
import { getAgents, getProperties } from "@/lib/data";
import { PropertyCard } from "@/components/property-card";
import { HeroMedia } from "@/components/hero-media";
import { siteAsset } from "@/lib/site-assets";
import { HeroSearch } from "@/components/hero-search";

export default async function Home() {
  const [properties, agents] = await Promise.all([getProperties(), getAgents()]);
  return <main>
    <section className="hero"><HeroMedia /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow light">SHORT-TERM STAYS, SOUTH AFRICA</p><h1>Find your place<br />to stay.</h1><p>Beautifully considered homes, apartments, and escapes in the places you want to be.</p></div><HeroSearch /></section>
    <section className="section featured"><div className="section-heading"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Featured stays</h2></div><Link href="/properties" className="text-link">View all properties <ArrowRight size={17} /></Link></div><div className="property-scroll">{properties.filter(p => p.featured).slice(0, 6).map(property => <PropertyCard property={property} key={property.id} />)}</div></section>
    <section className="section showcase"><div className="section-heading"><div><p className="eyebrow">NEXASTAY MOMENTS</p><h2>A glimpse of the good life.</h2></div><p className="showcase-note">Thoughtful stays. Lasting memories.</p></div><div className="showcase-grid"><figure className="showcase-feature"><Image src={siteAsset("ssstik.io_1787129766769.jpg")} alt="NexaStay lifestyle showcase" fill sizes="(max-width: 700px) 100vw, 48vw" /></figure><figure className="showcase-tall"><video autoPlay muted loop playsInline aria-label="NexaStay lifestyle video"><source src={siteAsset("ssstik.io_@nexastay_1787129668516.mp4")} type="video/mp4" /></video></figure><figure className="showcase-small"><video autoPlay muted loop playsInline aria-label="NexaStay lifestyle video"><source src={siteAsset("ssstik.io_@nexastay_1787129712411.mp4")} type="video/mp4" /></video></figure><figure className="showcase-small"><Image src={siteAsset("ssstik.io_1787129777366.jpg")} alt="NexaStay lifestyle showcase" fill sizes="(max-width: 700px) 50vw, 24vw" /></figure><figure className="showcase-quote"><Image src={siteAsset("ssstik.io_1787129780726.jpg")} alt="NexaStay lifestyle showcase" fill sizes="(max-width: 700px) 50vw, 24vw" /><figcaption>Stay a little<br /><em>longer.</em></figcaption></figure></div><div className="showcase-more"><p>More to discover</p><div className="showcase-more-rail">{["ssstik.io_1787129784653.jpg","ssstik.io_1787129788033.jpg","ssstik.io_1787129791608.jpg","ssstik.io_1787129794938.jpg"].map((image, index) => <figure key={image}><Image src={siteAsset(image)} alt={`NexaStay lifestyle showcase ${index + 6}`} fill sizes="(max-width: 700px) 68vw, 260px" /></figure>)}</div></div></section>
    <section className="section reasons"><p className="eyebrow">THE NEXASTAY DIFFERENCE</p><h2>Stays, made simpler.</h2><div className="reason-grid">{[["Verified stays","Every home is clearly presented, so you know what to expect."],["Local people","Get help from a real local agent when it matters."],["Simple enquiries","Find a stay and make a request in just a few minutes."],["South Africa focused","A collection shaped around the places people love here."]].map(([title, text]) => <article key={title}><Check size={20}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section agents-preview"><div className="section-heading"><div><p className="eyebrow">HERE TO HELP</p><h2>Meet your local experts</h2></div><Link href="/agents" className="text-link">Meet all agents <ArrowRight size={17} /></Link></div><div className="agent-row">{agents.map(agent => <article className="agent-card" key={agent.id}>{agent.image_url ? <Image src={agent.image_url} alt={agent.name} width={400} height={480}/> : <div className="agent-image-pending">{agent.name.split(" ").map((part: string) => part[0]).join("")}</div>}<div><p className="eyebrow">{agent.position}</p><h3>{agent.name}</h3><p><MapPin size={15}/> South Africa</p><Link href={`/agents/${agent.slug}`}>View profile</Link></div></article>)}</div></section>
    <section className="final-cta"><p className="eyebrow light">YOUR NEXT ESCAPE</p><h2>Your next stay is<br />closer than you think.</h2><Link className="button teal" href="/properties">Explore properties <ArrowRight size={18}/></Link></section>
  </main>;
}